//! Phase 3 (portable profile): export a re-importable backup of the user's
//! Claude Code setup + generated style, and apply such a bundle to a machine.
//!
//! Security: NEVER touch ~/.claude.json (it holds credentials). The bundle only
//! includes the style profile, skills, settings.json, and CLAUDE.md.
//!
//! This mirrors the verified logic in ember-deno's backend/portable.ts.

use std::path::{Path, PathBuf};

use serde::Serialize;
use serde_json::json;

use crate::profile::{self, StyleProfile};

#[derive(Debug, Serialize)]
pub struct ExportResult {
    pub bundle_dir: String,
    pub included: Vec<String>,
    pub skipped: Vec<String>,
}

#[derive(Debug, Serialize)]
pub struct ImportPlan {
    pub source_dir: String,
    pub applied: bool,
    pub actions: Vec<String>,
}

fn claude_home() -> Result<PathBuf, String> {
    dirs::home_dir()
        .map(|h| h.join(".claude"))
        .ok_or_else(|| "no home directory".to_string())
}

/// Copy a file or directory tree from `src` to `dest`.
pub(crate) fn copy_tree(src: &Path, dest: &Path) -> std::io::Result<()> {
    let meta = std::fs::metadata(src)?;
    if meta.is_dir() {
        std::fs::create_dir_all(dest)?;
        for entry in std::fs::read_dir(src)? {
            let entry = entry?;
            copy_tree(&entry.path(), &dest.join(entry.file_name()))?;
        }
    } else {
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::copy(src, dest)?;
    }
    Ok(())
}

/// Render the style profile as a portable, human-readable Markdown document.
fn style_markdown(p: &StyleProfile) -> String {
    let mut out = String::new();
    out.push_str(&format!("# {}\n\n{}\n\n", p.archetype.title, p.archetype.summary));
    out.push_str("## Traits\n\n");
    for t in &p.traits {
        out.push_str(&format!(
            "- **{}: {}** — {} _({})_\n",
            t.title, t.value, t.detail, t.evidence
        ));
    }
    out.push_str("\n## Stack\n\n");
    for l in &p.stack.languages {
        out.push_str(&format!("- {}: {}\n", l.language, l.count));
    }
    let used_skills: Vec<_> = p.skills.iter().filter(|s| s.usage_count > 0).collect();
    if !used_skills.is_empty() {
        out.push_str("\n## Skills relied on\n\n");
        for s in used_skills {
            out.push_str(&format!("- {} ({}×)\n", s.name, s.usage_count));
        }
    }
    out.push_str(&format!(
        "\n---\n_Generated by ember from local usage over {} days. No prompt text or credentials are included._\n",
        p.tenure_days
    ));
    out
}

/// Assets copied into / out of a bundle (relative to `~/.claude`). Credentials
/// (`.claude.json`) are deliberately excluded.
pub(crate) const ASSETS: [&str; 3] = ["skills", "settings.json", "CLAUDE.md"];

/// Write a portable profile bundle to `dest_dir`.
pub fn export_profile(dest_dir: String) -> Result<ExportResult, String> {
    let claude = claude_home()?;
    let dest = PathBuf::from(&dest_dir);
    std::fs::create_dir_all(&dest).map_err(|e| e.to_string())?;

    let mut included: Vec<String> = Vec::new();
    let mut skipped: Vec<String> = Vec::new();

    // 1. Style profile (json + markdown).
    let prof = profile::build_profile();
    std::fs::write(
        dest.join("profile.json"),
        serde_json::to_string_pretty(&prof).map_err(|e| e.to_string())?,
    )
    .map_err(|e| e.to_string())?;
    std::fs::write(dest.join("style.md"), style_markdown(&prof)).map_err(|e| e.to_string())?;
    included.push("profile.json".into());
    included.push("style.md".into());

    // 2. Copyable assets (no secrets).
    for name in ASSETS {
        let src = claude.join(name);
        if src.exists() {
            copy_tree(&src, &dest.join(name)).map_err(|e| e.to_string())?;
            included.push(name.into());
        } else {
            skipped.push(name.into());
        }
    }

    // 3. Manifest documenting the bundle and its deliberate exclusions.
    let manifest = json!({
        "kind": "ember-profile-bundle",
        "version": 1,
        "created_from": claude.to_string_lossy(),
        "included": included,
        "skipped": skipped,
        "excluded_for_security": [".claude.json (credentials)"],
    });
    std::fs::write(
        dest.join("manifest.json"),
        serde_json::to_string_pretty(&manifest).map_err(|e| e.to_string())?,
    )
    .map_err(|e| e.to_string())?;

    Ok(ExportResult {
        bundle_dir: dest.to_string_lossy().into_owned(),
        included,
        skipped,
    })
}

/// Apply a profile bundle to `~/.claude`. Defaults to a DRY RUN that only
/// reports what would change; pass `apply = true` to actually copy files.
pub fn import_profile(source_dir: String, apply: bool) -> Result<ImportPlan, String> {
    let claude = claude_home()?;
    let src = PathBuf::from(&source_dir);
    let mut actions: Vec<String> = Vec::new();

    for name in ASSETS {
        let s = src.join(name);
        if !s.exists() {
            continue;
        }
        let d = claude.join(name);
        let verb = if d.exists() { "overwrite" } else { "create" };
        actions.push(format!("{} {}", verb, d.display()));
        if apply {
            if d.exists() {
                let _ = if d.is_dir() {
                    std::fs::remove_dir_all(&d)
                } else {
                    std::fs::remove_file(&d)
                };
            }
            copy_tree(&s, &d).map_err(|e| e.to_string())?;
        }
    }

    Ok(ImportPlan {
        source_dir,
        applied: apply,
        actions,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn export_bundle_has_no_secrets() {
        let dir = std::env::temp_dir().join(format!("ember-export-test-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        let res = export_profile(dir.to_string_lossy().into_owned()).expect("export");
        eprintln!("included={:?} skipped={:?}", res.included, res.skipped);

        // profile.json + style.md must always be present.
        assert!(dir.join("profile.json").exists());
        assert!(dir.join("style.md").exists());
        assert!(dir.join("manifest.json").exists());

        // No credential-like strings anywhere in the bundle.
        let mut files = Vec::new();
        collect_files(&dir, &mut files);
        for f in &files {
            if let Ok(text) = std::fs::read_to_string(f) {
                for secret in [
                    "oauthAccount",
                    "userID",
                    "accessToken",
                    "refreshToken",
                    "sk-ant-",
                ] {
                    assert!(
                        !text.contains(secret),
                        "bundle file {} leaked secret pattern {}",
                        f.display(),
                        secret
                    );
                }
            }
        }

        // Dry-run import must not apply.
        let plan = import_profile(dir.to_string_lossy().into_owned(), false).expect("import");
        assert!(!plan.applied);
        eprintln!("import dry-run actions={:?}", plan.actions);

        let _ = std::fs::remove_dir_all(&dir);
    }

    fn collect_files(dir: &Path, out: &mut Vec<PathBuf>) {
        if let Ok(entries) = std::fs::read_dir(dir) {
            for e in entries.flatten() {
                let p = e.path();
                if p.is_dir() {
                    collect_files(&p, out);
                } else {
                    out.push(p);
                }
            }
        }
    }
}
